version: 0.1.{build}
image: Visual Studio 2017
install:
- ps: "Invoke-WebRequest -Uri 'https://aka.ms/cosmosdb-emulator' -OutFile 'cosmos-db.msi'\ncmd /c start /wait msiexec /i cosmos-db.msi /qn /quiet /norestart /log install.log  \nSet-Content -Value '\"C:\\Program Files\\Azure Cosmos DB Emulator\\CosmosDB.Emulator.exe\" /NoUI /NoExplorer /NoFirewall' -Path .\\startCosmosDb.cmd\nStart-Process -FilePath .\\startCosmosDb.cmd\n\n$attempt = 0\n$max = 3\nwhile(!$client.Connected -and $attempt -lt $max) {\n  try {    \n    $client = New-Object System.Net.Sockets.TcpClient([System.Net.Sockets.AddressFamily]::InterNetwork)\n    $attempt++; $client.Connect(\"127.0.0.1\", 8081); write-host \"CosmosDB started\"\n  }\n  catch {    \n    if($attempt -eq $max) {\n      write-host \"CosmosDB was not started\"; $client.Close(); return\n      }  \n    [int]$sleepTime = 5*$attempt\n    write-host \"CosmosDB is not started. Retry after $sleepTime seconds...\"\n    sleep $sleepTime;\n    $client.Close()        \n  }  \n}"
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    dotnet test tests\Cosmonaut.Unit

    dotnet test tests\Cosmonaut.System
